language: ruby
rvm:
  - 2.1.1
before_install:
  - "gem update --system"
  - "gem update bundler"
before_script:
  - "bundle exec rake db:test:load"
notifications:
  hipchat: 89d684618c0efae42e66b30900961c@RailsSchool
