language: ruby
rvm:
  - 1.9.3
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "bundle exec rake db:test:load"
notifications:
  hipchat: 89d684618c0efae42e66b30900961c@RailsSchool
